### PR TITLE
Small tweaks and dependency information fix

### PR DESCRIPTION
**Pull request by kiwistrongis**
Just wanted to run this by you (@tuxmark5) before pushing to master. The `cabal install usb-1.2.0.1` part in the readme is correct, right?

### CODE REVIEW

**Comment by tuxmark5** [comment]
Overall this looks good, however you shouldn't need to manually install dependencies using cabal. "cabal install" command when executed in ApexCtl's folder should automatically on it's own download & install all necessary dependencies and then compile & install ApexCtl to ~/.cabal/bin

**Comment by kiwistrongis** [comment]
Well the udev rules only work when apexctl's installed to `/usr/local/sbin`. At the moment the installation process for new users (ones who've never used cabal before) goes kinda like this:

```bash
# install system deps

# install haskell deps
cabal update
cabal install usb-1.2.0.1 cmdargs

# build
cabal configure
cabal build

# install udev rules, xmodmap, and binary
sudo make install 
```

Is there some way to make that smoother?

**Comment by tuxmark5** [comment]
These three steps:
```
cabal install usb-1.2.0.1 cmdargs
cabal configure
cabal build
```

Can be merged into:
`cabal install`

**Comment by kiwistrongis** [comment]
But `cabal install` also installs apexctl into `~/.cabal/bin` or something like it, does it not? Also, `cabal build` is working fine, but `cabal install` gives me this error:

```
setup-Simple-Cabal-1.18.1.5-x86_64-linux-ghc-7.8.4: dist/package.conf.inplace:
inappropriate type
```

**Pull request merged**
